# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addCourses.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(315, 226)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/planner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(dialog)
        self.formLayout.setObjectName("formLayout")
        self.coursesLbl = QtWidgets.QLabel(dialog)
        self.coursesLbl.setObjectName("coursesLbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.coursesLbl)
        self.coursesTxtEdit = QtWidgets.QTextEdit(dialog)
        self.coursesTxtEdit.setObjectName("coursesTxtEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.coursesTxtEdit)
        self.planBtn = QtWidgets.QPushButton(dialog)
        self.planBtn.setObjectName("planBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.planBtn)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Add Course"))
        self.coursesLbl.setText(_translate("dialog", "Courses: "))
        self.planBtn.setText(_translate("dialog", "Check"))
import resources_rc
